### ISSUE TITLE
Only Download Last: N episodes

### ISSUE THREAD

**Issue by roblammert** [cnovel/PodcastBulkDownloader#34]
**Is your feature request related to a problem? Please describe.**
Not related to a problem per se

**Describe the solution you'd like**
Be allowed to chose to download a specific number of the latest podcasts, such as the last 2 episodes, or the last episode.

**Describe alternatives you've considered**
NA

**Additional context**
I don't want to keep every single podcast file on the disk just so it won't download them. I am hoping to just keep ones that I like and use something in the gui to choose between download all or select number of latest episodes (last 3 episodes, last 1 episode, etc).  I personally believe that this will round out this great tool!

**Comment by cnovel** [comment]
Thanks for the feedback :) It's been a while so I can't make any promises, but I'll try to add this feature. Workaround in the meantime: you can cancel the download as the podcasts are downloaded most of the times from most recent to least recent.

**Comment by cnovel** [comment]
@roblammert This has been implemented, I'm waiting on some feedback on #35 before releasing v0.5

**Comment by cnovel** [comment]
@roblammert v0.5 is released, sorry for the delay! There's now an option for downloading only the last n episodes.
