### ISSUE TITLE
Exe won’t open 

### ISSUE THREAD

**Issue by chemicalsam** [cnovel/PodcastBulkDownloader#35]
**Describe the bug**
Clicking on the GUI OR CLI exe don’t do anything. 

**To Reproduce**
-I downloaded the zip
-Extracted it
-Tried to open the exe
-Nothing happens 

**System Information:**
Windows 10 

**Additional context**

**Comment by cnovel** [comment]
Hi @chemicalsam, sorry about that! If you try to run `PodcastBulkDownloaderCLI.exe -h` from cmd.exe, does it show something?

**Comment by chemicalsam** [comment]
![FB0EAAC6-6F4E-4550-8229-565E11369A2C](https://user-images.githubusercontent.com/67978865/118571710-acd57580-b74c-11eb-859b-6d9b980f5c37.png)

**Comment by cnovel** [comment]
The message you have indicates that PodcastBulkDownloaderCLI.exe is not in the folder you are in. This is what it should look like

https://user-images.githubusercontent.com/5690282/118590074-04ea9700-b7a2-11eb-8cad-ff75c2eaaa55.mp4
