### ISSUE TITLE
Some podcasts get 403 or 406 errors when fetching

### ISSUE THREAD

**Issue by talvola** [cnovel/PodcastBulkDownloader#39]
I've seen a couple podcasts which get errors when fetching, even though they seem to load file in browsers:

http://hobbsnfriends.com/feed/podcast/
https://saveforhalf.com/feed/podcast/

are two examples.    Errors are:

[2021-07-19 14:36:14][INFO] Fetch info
[2021-07-19 14:36:15][ERROR] Failed to access URL (code 403)

or

[2021-07-19 14:36:44][INFO] Fetch info
[2021-07-19 14:36:44][ERROR] Failed to access URL (code 406)

This is on v0.4 on Windows 10.

I don't know enough about RSS feeds to know if it's the format of the file, or something else.    Chrome, wget, etc. all can fetch the file using that URL.

**Comment by cnovel** [comment]
Hi @talvola, sorry it took so long for me to look at this issue. I'm able to reproduce it and I have a fix on the way. Expect it to be released during the summer.

**Comment by cnovel** [comment]
@talvola scratch that, v0.6 is now available 😄
