### ISSUE TITLE
Emoji's causing "Argument must be a string" errors

### ISSUE THREAD

**Issue by KierenConnell** [cnovel/PodcastBulkDownloader#40]
**Describe the bug**
Emoji's in podcast tile name cause "Argument must be a string" errors

**To Reproduce**
1. Download from https://rss.art19.com/life-is-short-with-justin-long
2. See error

**Expected behavior**
Downloader to ignore emoji's - Or rename

**Screenshots**
![image](https://user-images.githubusercontent.com/46445781/147107820-34504cfa-92d6-4042-9351-2c0de8f7a489.png)

**System Information:**
Windows 10

**Comment by cnovel** [comment]
Hi @KierenConnell

I'm able to reproduce the issue. It's not related to the emojis: I'm expecting a content-length field in the header file that I don't get. I'm changing the way I download the mp3 file. I expect a release during the summer.

**Comment by cnovel** [comment]
@KierenConnell v0.6 is released and fix this issue 😄
