### ISSUE TITLE
Reversed slashes in the GUI version

### ISSUE THREAD

**Issue by anewuser** [cnovel/PodcastBulkDownloader#54]
I selected the folder with the `...` directory picker:

![ad](https://user-images.githubusercontent.com/6733770/174696821-20d79a25-0f27-4ff2-b469-5d9c99399b28.png)

Windows 10 21H2
PodcastBulkDownloader v0.6

**Comment by cnovel** [comment]
Hi @anewuser,

Not really a bug as this is more visual than a real problem. I flagged it as enhancement and will work so that / are all in the same direction. Target is v0.7
