### ISSUE TITLE
Long titles with special caracters do not always work

### ISSUE THREAD

**Issue by oysmik** [cnovel/PodcastBulkDownloader#61]
Example:
[ERROR] [Errno 22] Invalid argument: 'D:\\Podcast-Backup-2021\\Wolfgang Wee Uncut\\Simen Sandelien Rasismedebatten, Likestilling i Norge, Norsk Presse, Objektiv Journalistikk Med Slagside, Læreryrket, Klimadebatten, Sløseriombudsmannen, Overrepresentasjon I Kriminalstatistikken, Etiopia, Innvandring og Integrering, Identitetspolitikk.mp3'
PS D:\Podcast-Backup-2021\PodcastBulkDownloader-v0.7>

Source:
https://feed.pippa.io/public/shows/5c84098aab4c3efd34fbc464

Running this command:
.\PodcastBulkDownloaderCLI.exe -f "D:\Podcast-Backup-2021\Wolfgang Wee Uncut" --url https://feed.pippa.io/public/shows/5c84098aab4c3efd34fbc464

**Comment by cnovel** [comment]
Hello @oysmik thanks for reporting the issue. I'll try to look at it during this week. However, I fear the solution will be cutting the episode name: [Windows has some limitations regarding path length](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry).
