### ISSUE TITLE
Download Only First n episodes

### ISSUE THREAD

**Issue by TotoDown27** [cnovel/PodcastBulkDownloader#63]
**Is your feature request related to a problem? Please describe.**
I follow a number of podcasts and download to mp3 player for when i walk. At present I have to download all episodes to get newest.

**Describe the solution you'd like**
Download only the First n Episodes

**Describe alternatives you've considered**
There is no alternative

**Additional context**
Only additional comment is that the program is beyond brilliant.

**Comment by cnovel** [comment]
Hi, sorry I missed this issue.

Your use case should be covered by the _Download only last X episodes_ feature
![image](https://user-images.githubusercontent.com/5690282/218270125-d560640d-7d92-4f98-a257-71e0bbc18983.png)

If not, I'm not understanding what your issue is. Thanks.
