### ISSUE TITLE
Do you think you may add SoundClod support in the future?

### ISSUE THREAD

**Issue by ElysRealm** [cnovel/PodcastBulkDownloader#70]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
I'd really like to see this integrated with SoundCloud. Why? Well some podcasts, particularly longer ones have really long running shows (like one I listen to has been around since approximately 2011. However, sometimes episodes go missing, get deleted, or paywalled (which is fine, it's the Podcast holders right). In my case I know of a podcast that has a good amount of episodes on all major platforms, but the rest of it's back catalog isn't available _unless_ you go to SoundCloud because it has been auto-uploading there for years apparently.

Suffice to say sometimes when it comes to Podcasts, SoundCloud sometimes has episodes that can't be found anywhere else. I'd really like to see this feature added, and if not I may consider making my own or forking this (with permission obv.)

**Describe alternatives you've considered**
JDownloader 2 - It works but the UI is clunky and overall I kind of use it only when nothing else works lol.
Others - I know there exists other SoundCloud downloader apps, and even repos on GitHub but most of them don't work for some reason or another.

**Additional context**
Cheers, you're doing great! Glad to see this app. Very useful :).

**Comment by cnovel** [comment]
Hello,
Unfortunately, Soundcloud is very different from an RSS feed, and supporting this would be a lot of work as of right now. Have a look at [yt-dlp](https://github.com/yt-dlp/yt-dlp), I know it is a cmd line interface but I think they are supporting SoundCloud.

Thanks
