### ISSUE TITLE
Spotify RSS

### ISSUE THREAD

**Issue by dsakura** [cnovel/PodcastBulkDownloader#81]
Hello! Im lost about the podcast rss... Some instructions about it will be nice in the readme. I can't find the podcast's rss, I haven't found anything about them in the searches.

Many thanks

**Comment by cnovel** [comment]
Hello @dsakura Spotify does not provide RSS feeds for podcasts hosted on its platform. There's even debate in the podcast community that because of that, Spotify podcasts should not be called podcasts. RSS links are provided by the podcast authors. If you can't find it, please email the authors :)
